/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface NotificationPreference {
    notificationMuted: boolean;
    eyeRestInterval: bigint;
    notificationVolume: bigint;
    postureResetInterval: bigint;
    stretchInterval: bigint;
    walkInterval: bigint;
    standInterval: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface WellbeingSession {
    startTime: Time;
    duration: bigint;
    endTime: Time;
    suggestedAction: string;
    breaksTaken: bigint;
}
export interface SocialMediaGoal {
    mindfulBreaks: bigint;
    dailyLimit: bigint;
}
export interface ReflectionEntry {
    date: Time;
    bodyFeeling: bigint;
    notes: string;
}
export interface UserProfile {
    name: string;
    createdAt: Time;
    summaryFrequency: SummaryFrequency;
}
export interface http_header {
    value: string;
    name: string;
}
export enum SummaryFrequency {
    daily = "daily",
    weekly = "weekly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteReflection(reflectionId: bigint): Promise<void>;
    deleteSession(sessionId: bigint): Promise<void>;
    fetchExternalMotivationalQuote(): Promise<string>;
    fetchExternalReflectionPrompt(): Promise<string>;
    getAllReflections(): Promise<Array<ReflectionEntry>>;
    getAllSessions(): Promise<Array<WellbeingSession>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        averageBodyFeeling: bigint;
        averageSittingDuration: bigint;
        socialMediaGoal?: SocialMediaGoal;
        motivationalQuote: string;
        reflectionPromptTemplate: string;
        totalSessions: bigint;
        totalBreaks: bigint;
    }>;
    getNotificationPreferences(): Promise<NotificationPreference | null>;
    getReflection(id: bigint): Promise<ReflectionEntry | null>;
    getReflectionsByDateRange(startDate: Time, endDate: Time): Promise<Array<ReflectionEntry>>;
    getSession(id: bigint): Promise<WellbeingSession | null>;
    getSocialMediaGoal(): Promise<SocialMediaGoal | null>;
    isCallerAdmin(): Promise<boolean>;
    resetWellbeingAssistant(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveNotificationPreferences(standInterval: bigint, walkInterval: bigint, stretchInterval: bigint, eyeRestInterval: bigint, postureResetInterval: bigint, notificationVolume: bigint, notificationMuted: boolean): Promise<void>;
    saveReflection(date: Time, bodyFeeling: bigint, notes: string): Promise<bigint>;
    saveSession(startTime: Time, endTime: Time, duration: bigint, breaksTaken: bigint, suggestedAction: string): Promise<bigint>;
    searchSessionsByAction(action: string): Promise<Array<WellbeingSession>>;
    setSocialMediaGoal(dailyLimit: bigint, mindfulBreaks: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSummaryFrequency(newFrequency: SummaryFrequency): Promise<void>;
}
import type { NotificationPreference as _NotificationPreference, ReflectionEntry as _ReflectionEntry, SocialMediaGoal as _SocialMediaGoal, SummaryFrequency as _SummaryFrequency, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WellbeingSession as _WellbeingSession } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteReflection(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReflection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReflection(arg0);
            return result;
        }
    }
    async deleteSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSession(arg0);
            return result;
        }
    }
    async fetchExternalMotivationalQuote(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchExternalMotivationalQuote();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchExternalMotivationalQuote();
            return result;
        }
    }
    async fetchExternalReflectionPrompt(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchExternalReflectionPrompt();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchExternalReflectionPrompt();
            return result;
        }
    }
    async getAllReflections(): Promise<Array<ReflectionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReflections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReflections();
            return result;
        }
    }
    async getAllSessions(): Promise<Array<WellbeingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        averageBodyFeeling: bigint;
        averageSittingDuration: bigint;
        socialMediaGoal?: SocialMediaGoal;
        motivationalQuote: string;
        reflectionPromptTemplate: string;
        totalSessions: bigint;
        totalBreaks: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationPreferences(): Promise<NotificationPreference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationPreferences();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationPreferences();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReflection(arg0: bigint): Promise<ReflectionEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReflection(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReflection(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReflectionsByDateRange(arg0: Time, arg1: Time): Promise<Array<ReflectionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReflectionsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReflectionsByDateRange(arg0, arg1);
            return result;
        }
    }
    async getSession(arg0: bigint): Promise<WellbeingSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSocialMediaGoal(): Promise<SocialMediaGoal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialMediaGoal();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialMediaGoal();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetWellbeingAssistant(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetWellbeingAssistant();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetWellbeingAssistant();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveNotificationPreferences(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNotificationPreferences(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNotificationPreferences(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async saveReflection(arg0: Time, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReflection(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReflection(arg0, arg1, arg2);
            return result;
        }
    }
    async saveSession(arg0: Time, arg1: Time, arg2: bigint, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSession(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSession(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async searchSessionsByAction(arg0: string): Promise<Array<WellbeingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSessionsByAction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSessionsByAction(arg0);
            return result;
        }
    }
    async setSocialMediaGoal(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSocialMediaGoal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSocialMediaGoal(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSummaryFrequency(arg0: SummaryFrequency): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSummaryFrequency(to_candid_SummaryFrequency_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSummaryFrequency(to_candid_SummaryFrequency_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_SummaryFrequency_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SummaryFrequency): SummaryFrequency {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SocialMediaGoal]): SocialMediaGoal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NotificationPreference]): NotificationPreference | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReflectionEntry]): ReflectionEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WellbeingSession]): WellbeingSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageBodyFeeling: bigint;
    averageSittingDuration: bigint;
    socialMediaGoal: [] | [_SocialMediaGoal];
    motivationalQuote: string;
    reflectionPromptTemplate: string;
    totalSessions: bigint;
    totalBreaks: bigint;
}): {
    averageBodyFeeling: bigint;
    averageSittingDuration: bigint;
    socialMediaGoal?: SocialMediaGoal;
    motivationalQuote: string;
    reflectionPromptTemplate: string;
    totalSessions: bigint;
    totalBreaks: bigint;
} {
    return {
        averageBodyFeeling: value.averageBodyFeeling,
        averageSittingDuration: value.averageSittingDuration,
        socialMediaGoal: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.socialMediaGoal)),
        motivationalQuote: value.motivationalQuote,
        reflectionPromptTemplate: value.reflectionPromptTemplate,
        totalSessions: value.totalSessions,
        totalBreaks: value.totalBreaks
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Time;
    summaryFrequency: _SummaryFrequency;
}): {
    name: string;
    createdAt: Time;
    summaryFrequency: SummaryFrequency;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        summaryFrequency: from_candid_SummaryFrequency_n6(_uploadFile, _downloadFile, value.summaryFrequency)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    daily: null;
} | {
    weekly: null;
}): SummaryFrequency {
    return "daily" in value ? SummaryFrequency.daily : "weekly" in value ? SummaryFrequency.weekly : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_SummaryFrequency_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SummaryFrequency): _SummaryFrequency {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: Time;
    summaryFrequency: SummaryFrequency;
}): {
    name: string;
    createdAt: _Time;
    summaryFrequency: _SummaryFrequency;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        summaryFrequency: to_candid_SummaryFrequency_n17(_uploadFile, _downloadFile, value.summaryFrequency)
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SummaryFrequency): {
    daily: null;
} | {
    weekly: null;
} {
    return value == SummaryFrequency.daily ? {
        daily: null
    } : value == SummaryFrequency.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
