/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NotificationPreference {
  'notificationMuted' : boolean,
  'eyeRestInterval' : bigint,
  'notificationVolume' : bigint,
  'postureResetInterval' : bigint,
  'stretchInterval' : bigint,
  'walkInterval' : bigint,
  'standInterval' : bigint,
}
export interface ReflectionEntry {
  'date' : Time,
  'bodyFeeling' : bigint,
  'notes' : string,
}
export interface SocialMediaGoal {
  'mindfulBreaks' : bigint,
  'dailyLimit' : bigint,
}
export type SummaryFrequency = { 'daily' : null } |
  { 'weekly' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'summaryFrequency' : SummaryFrequency,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WellbeingSession {
  'startTime' : Time,
  'duration' : bigint,
  'endTime' : Time,
  'suggestedAction' : string,
  'breaksTaken' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteReflection' : ActorMethod<[bigint], undefined>,
  'deleteSession' : ActorMethod<[bigint], undefined>,
  'fetchExternalMotivationalQuote' : ActorMethod<[], string>,
  'fetchExternalReflectionPrompt' : ActorMethod<[], string>,
  'getAllReflections' : ActorMethod<[], Array<ReflectionEntry>>,
  'getAllSessions' : ActorMethod<[], Array<WellbeingSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'averageBodyFeeling' : bigint,
      'averageSittingDuration' : bigint,
      'socialMediaGoal' : [] | [SocialMediaGoal],
      'motivationalQuote' : string,
      'reflectionPromptTemplate' : string,
      'totalSessions' : bigint,
      'totalBreaks' : bigint,
    }
  >,
  'getNotificationPreferences' : ActorMethod<[], [] | [NotificationPreference]>,
  'getReflection' : ActorMethod<[bigint], [] | [ReflectionEntry]>,
  'getReflectionsByDateRange' : ActorMethod<
    [Time, Time],
    Array<ReflectionEntry>
  >,
  'getSession' : ActorMethod<[bigint], [] | [WellbeingSession]>,
  'getSocialMediaGoal' : ActorMethod<[], [] | [SocialMediaGoal]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetWellbeingAssistant' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveNotificationPreferences' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, boolean],
    undefined
  >,
  'saveReflection' : ActorMethod<[Time, bigint, string], bigint>,
  'saveSession' : ActorMethod<[Time, Time, bigint, bigint, string], bigint>,
  'searchSessionsByAction' : ActorMethod<[string], Array<WellbeingSession>>,
  'setSocialMediaGoal' : ActorMethod<[bigint, bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSummaryFrequency' : ActorMethod<[SummaryFrequency], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];