/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ReflectionEntry = IDL.Record({
  'date' : Time,
  'bodyFeeling' : IDL.Nat,
  'notes' : IDL.Text,
});
export const WellbeingSession = IDL.Record({
  'startTime' : Time,
  'duration' : IDL.Nat,
  'endTime' : Time,
  'suggestedAction' : IDL.Text,
  'breaksTaken' : IDL.Nat,
});
export const SummaryFrequency = IDL.Variant({
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'summaryFrequency' : SummaryFrequency,
});
export const SocialMediaGoal = IDL.Record({
  'mindfulBreaks' : IDL.Nat,
  'dailyLimit' : IDL.Nat,
});
export const NotificationPreference = IDL.Record({
  'notificationMuted' : IDL.Bool,
  'eyeRestInterval' : IDL.Nat,
  'notificationVolume' : IDL.Nat,
  'postureResetInterval' : IDL.Nat,
  'stretchInterval' : IDL.Nat,
  'walkInterval' : IDL.Nat,
  'standInterval' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteReflection' : IDL.Func([IDL.Nat], [], []),
  'deleteSession' : IDL.Func([IDL.Nat], [], []),
  'fetchExternalMotivationalQuote' : IDL.Func([], [IDL.Text], []),
  'fetchExternalReflectionPrompt' : IDL.Func([], [IDL.Text], []),
  'getAllReflections' : IDL.Func([], [IDL.Vec(ReflectionEntry)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(WellbeingSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'averageBodyFeeling' : IDL.Nat,
          'averageSittingDuration' : IDL.Nat,
          'socialMediaGoal' : IDL.Opt(SocialMediaGoal),
          'motivationalQuote' : IDL.Text,
          'reflectionPromptTemplate' : IDL.Text,
          'totalSessions' : IDL.Nat,
          'totalBreaks' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getNotificationPreferences' : IDL.Func(
      [],
      [IDL.Opt(NotificationPreference)],
      ['query'],
    ),
  'getReflection' : IDL.Func([IDL.Nat], [IDL.Opt(ReflectionEntry)], ['query']),
  'getReflectionsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(ReflectionEntry)],
      ['query'],
    ),
  'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(WellbeingSession)], ['query']),
  'getSocialMediaGoal' : IDL.Func([], [IDL.Opt(SocialMediaGoal)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetWellbeingAssistant' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveNotificationPreferences' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'saveReflection' : IDL.Func([Time, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'saveSession' : IDL.Func(
      [Time, Time, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'searchSessionsByAction' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WellbeingSession)],
      ['query'],
    ),
  'setSocialMediaGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSummaryFrequency' : IDL.Func([SummaryFrequency], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReflectionEntry = IDL.Record({
    'date' : Time,
    'bodyFeeling' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const WellbeingSession = IDL.Record({
    'startTime' : Time,
    'duration' : IDL.Nat,
    'endTime' : Time,
    'suggestedAction' : IDL.Text,
    'breaksTaken' : IDL.Nat,
  });
  const SummaryFrequency = IDL.Variant({
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'summaryFrequency' : SummaryFrequency,
  });
  const SocialMediaGoal = IDL.Record({
    'mindfulBreaks' : IDL.Nat,
    'dailyLimit' : IDL.Nat,
  });
  const NotificationPreference = IDL.Record({
    'notificationMuted' : IDL.Bool,
    'eyeRestInterval' : IDL.Nat,
    'notificationVolume' : IDL.Nat,
    'postureResetInterval' : IDL.Nat,
    'stretchInterval' : IDL.Nat,
    'walkInterval' : IDL.Nat,
    'standInterval' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteReflection' : IDL.Func([IDL.Nat], [], []),
    'deleteSession' : IDL.Func([IDL.Nat], [], []),
    'fetchExternalMotivationalQuote' : IDL.Func([], [IDL.Text], []),
    'fetchExternalReflectionPrompt' : IDL.Func([], [IDL.Text], []),
    'getAllReflections' : IDL.Func([], [IDL.Vec(ReflectionEntry)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(WellbeingSession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'averageBodyFeeling' : IDL.Nat,
            'averageSittingDuration' : IDL.Nat,
            'socialMediaGoal' : IDL.Opt(SocialMediaGoal),
            'motivationalQuote' : IDL.Text,
            'reflectionPromptTemplate' : IDL.Text,
            'totalSessions' : IDL.Nat,
            'totalBreaks' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getNotificationPreferences' : IDL.Func(
        [],
        [IDL.Opt(NotificationPreference)],
        ['query'],
      ),
    'getReflection' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ReflectionEntry)],
        ['query'],
      ),
    'getReflectionsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(ReflectionEntry)],
        ['query'],
      ),
    'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(WellbeingSession)], ['query']),
    'getSocialMediaGoal' : IDL.Func([], [IDL.Opt(SocialMediaGoal)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetWellbeingAssistant' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveNotificationPreferences' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'saveReflection' : IDL.Func([Time, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'saveSession' : IDL.Func(
        [Time, Time, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'searchSessionsByAction' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WellbeingSession)],
        ['query'],
      ),
    'setSocialMediaGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSummaryFrequency' : IDL.Func([SummaryFrequency], [], []),
  });
};

export const init = ({ IDL }) => { return []; };